- name: configure dispatch server
  become: yes
  hosts: dispatch
  # connection: local
  tasks: 
  - name: install golang
    ansible.builtin.dnf:
      name: golang
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      home: /app
      system: true
      shell: /sbin/nologin

  - name: create an directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the application code url
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
      dest: /tmp/dispatch.zip

  - name: unzip the downloaded code
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes
    
  - name: download golang dependencies
    ansible.builtin.shell: go mod init dispatch ; go get ; go build
    args:
        chdir: /app

  - name: copy dispatch service
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service

  - name: daemon reload service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable the service
    ansible.builtin.service:
      name: dispatch
      state: started
      enabled: yes

    
