- name: configure frontend server
  become: yes
  hosts: frontend
  # connection: local
  tasks:
  - name: disable and enable nginx configuration
    ansible.builtin.shell: dnf module disable nginx -y ; dnf module enable nginx:1.24 -y

  - name: install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: present
  
  - name: start and enable nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: Remove file 
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unarchive file that downloaded
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes 

  - name: remove default nginx conf
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy and create reverse proxy server
    ansible.builtin.copy:
      src: nginx.service
      dest: /etc/nginx/nginx.conf

  - name: restart nginx service
    ansible.builtin.service:
      name: nginx
      state: restarted
      