- name: configure user component
  hosts: user
  become: yes
  # connection: local
  tasks:
  - name: disable default nodejs version
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable default nodejs version
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs version
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      home: /app
      system: true
      shell: /sbin/nologin

  - name: create an app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: download application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: unzip the downloaded code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    ansible.builtin.command: npm install
    args:
        chdir: /app

  - name: copy user service to system directory
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: reload systemd daemon
    ansible.builtin.systemd:
      daemon_reload: true
   
   
  - name: start and enable the service
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes

